# Generated by Django 3.1.7 on 2021-04-07 08:14

from django.db import migrations, models
import foodgram.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20210402_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=foodgram.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.CharField(choices=[('Завтрак', 'Breakfast'), ('Обед', 'Lunch'), ('Ужин', 'Dinner')], default='Обед', max_length=7),
        ),
    ]
