# Generated by Django 3.1.7 on 2021-04-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20210422_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddField(
            model_name='tag',
            name='style',
            field=models.CharField(default=134, max_length=100),
            preserve_default=False,
        ),
    ]
